### ISSUE TITLE
Failing to fully run using a 19G MySQL 8 slow query log

### ISSUE THREAD

**Issue by sulavvr** [devops-works/slowql#12]
This runs for a while, but then crashes, anywhere to see what specifically is causing this to panic?

```
$ ./slowql -db {database} -f /tmp/slowquery.log -h {hostname} -u root -w 2500 -x 5 -k mysql --no-dry-run -p
```

```
INFO[0008] getting real execution time                  
INFO[0192] 2500 workers will be created                 
WARN[0192] no-dry-run flag found, queries will be executed 
INFO[0192] replay started on Mon Sep 25 19:51:01        
INFO[0192] estimated time of end: Mon Sep 25 20:03:05   
528578 / 20617071 [▉▉▉▉ ..........................................................................................................................................................................................] 1787 p/s ETA 3h7m22s 2.56%panic: send on closed channel

goroutine 8 [running]:
github.com/devops-works/slowql/database/mysql.(*Database).ParseBlocks(0xc0001262a0, 0x0)
        /home/runner/work/slowql/slowql/database/mysql/mysql.go:46 +0x8b
created by github.com/devops-works/slowql.NewParser
        /home/runner/work/slowql/slowql/slowql.go:71 +0x44f
```

**Comment by sulavvr** [comment]
@leucos I'm using the latest, v0.1.2, so the commit looks right.

I'm running this against an RDS MySQL with a 16k concurrent connections ability, so the connection shouldn't be a problem. The QPS is pretty high, the log has about ~5M queries, and the slow log capture duration is for about 30 minutes.

The last time I tried with lower threads, the replayer took a very long to replay the queries, much longer than the actual duration.

The MySQL server is fine, there's nothing wrong with it when the replayer crashes.

**Comment by leucos** [comment]
You are very welcome @sulavvr . It is always interesting to get feedback.
The principle behind the replayer is to ship queries X (`-x`) times faster than seen in the log.

This being said, there are limitations:

- the server might not cope with the new rate
- the replay might not cope with the original query log rate if the server it was recorded on was very fast

About the latter, the current algo is not very optimized and might get quickly overwhelmed if the original server was very fast. so the end result you get ( +53.76% speed increase) could be considered a minimum, since the replayer might throttle the server.

There is some room for improvement here ! I hope to find some time for this one of these days.

Have fun with your RDS monster ;)
